language: python
dist: xenial

stages:
  - lint
  - test

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
    - "$HOME/.cache/pre-commit"

install:
  - pip install poetry
  - poetry install

script: pytest tests/

jobs:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8-dev"

    - stage: lint
      python: "3.7"
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files