site_name: Foxcross
site_description: AsyncIO serving for data science models
site_author: LAAC Technology
site_url: https://www.foxcross.dev

theme:
  name: 'material'

repo_name: laactech/foxcross
repo_url: https://github.com/laactech/foxcross

nav:
  - Home: index.md
  - Serving: serving.md
  - Pandas Serving: pandas-serving.md
  - Advanced Usage: advanced-usage.md
  - Release Notes: release-notes.md

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.inlinehilite
