site_name: Foxcross
site_description: Asyncio serving for data science models
site_author: LAAC Technology
site_url: https://www.foxcross.dev

theme:
  name: 'material'

repo_name: laactech/foxcross
repo_url: https://github.com/laactech/foxcross

nav:
  - Home: index.md

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.inlinehilite
